# Generated by Django 5.2.3 on 2025-07-02 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacao', '0003_alter_personas_numero_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(choices=[('Antioquia', 'Antioquia'), ('Atlantico', 'Atlantico'), ('Bogota', 'Bogota'), ('Bolivar', 'Bolivar'), ('Caldas', 'Caldas'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Cordoba', 'Cordoba'), ('Huila', 'Huila'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(choices=[('Colombia', 'Colombia'), ('Venezuela', 'Venezuela'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipos_documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='quien_diligencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('Comercializador', 'Comercializador'), ('Transformador', 'Transformador'), ('Exportador', 'Exportador')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_persona',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Juridica', 'Juridica')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.CharField(default='SIN_DOCUMENTO', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(choices=[('Medellin', 'Medellin'), ('Barranquilla', 'Barranquilla'), ('Bogota', 'Bogota'), ('Cartagena', 'Cartagena'), ('Manizales', 'Manizales'), ('Popayan', 'Popayan'), ('Valledupar', 'Valledupar'), ('Monteria', 'Monteria'), ('Neiva', 'Neiva'), ('Santa Marta', 'Santa Marta'), ('Villavicencio', 'Villavicencio')], max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='cacao.departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='cacao.paises'),
        ),
        migrations.AddField(
            model_name='personas',
            name='nombre_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='cacao.paises'),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_de_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas_tipos_documentos', to='cacao.tipos_documentos'),
        ),
    ]
