# Generated by Django 5.2.3 on 2025-07-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacao', '0004_departamentos_paises_tipos_documentos_personas_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_documentos',
            name='tipo_de_documento',
            field=models.CharField(choices=[('Cedula Ciudadania', 'Cedula Ciudadania'), ('Cedula Extranjeria', 'Cedula Extranjeria'), ('Nit', 'Nit'), ('Pasaporte', 'Pasaporte')], max_length=50),
        ),
    ]
