# Generated by Django 5.2.3 on 2025-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacao', '0002_personas_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
